org: rahulmathews
app: aws-python-neo
service: aws-python-neo

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  environment:
    NEO4J_URI: ${param:NEO4J_URI}
    NEO4J_USER: ${param:NEO4J_USER}
    NEO4J_PASSWORD: ${param:NEO4J_PASSWORD}
    NEO4J_DATABASE: ${param:NEO4J_DATABASE}
  memorySize: 128
  timeout: 30

functions:
  api:
    handler: wsgi_handler.handler
    url: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
